import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./reset.css";
import StyledComponentsRegistry from "@/lib/registry";
import Sidebar from "@/components/Sidebar";
import Dim from "@/components/Dim";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          {children}
          <Dim />
          <Sidebar />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
