export const dummyTrade = [
  {
    name: "Bybit",
    averageRefund: 720000,
    image: require("./assets/bybit.webp"),
    tag: "인기거래소 🔥",
    payback: "30%",
    discount: "20%",
    closing: "93%",
  },
  {
    name: "DeepCoin",
    averageRefund: 720000,
    image: require("./assets/deepCoin.webp"),
    tag: "신규 제휴 ⭐️",
    payback: "70%",
    discount: "50%",
    closing: "15%",
  },
  {
    name: "Bitget",
    averageRefund: 720000,
    image: require("./assets/bitget.webp"),
    tag: "인기거래소 🔥",
    payback: "54%",
    discount: "50%",
    closing: "87%",
  },
  {
    name: "OKX",
    averageRefund: 720000,
    image: require("./assets/okx.webp"),
    tag: "준비금 증명 🧳",
    payback: "54%",
    // discount: "20%",
    closing: "98%",
  },
  {
    name: "BingX",
    averageRefund: 720000,
    image: require("./assets/bingx.webp"),
    tag: "추천거래소 👏🏻",
    payback: "60%",
    closing: "72%",
  },
  {
    name: "Bybit",
    averageRefund: 720000,
    image: require("./assets/bybit.webp"),
    tag: "인기거래소 🔥",
    payback: "30%",
    discount: "20%",
  },
  {
    name: "Bybit",
    averageRefund: 720000,
    image: require("./assets/bybit.webp"),
    tag: "인기거래소 🔥",
    payback: "30%",
    discount: "20%",
  },
  {
    name: "Bybit",
    averageRefund: 720000,
    image: require("./assets/bybit.webp"),
    tag: "인기거래소 🔥",
    payback: "30%",
    discount: "20%",
  },
  {
    name: "Bybit",
    averageRefund: 720000,
    image: require("./assets/bybit.webp"),
    tag: "인기거래소 🔥",
    payback: "30%",
    discount: "20%",
  },
  {
    name: "Bybit",
    averageRefund: 720000,
    image: require("./assets/bybit.webp"),
    tag: "인기거래소 🔥",
    payback: "30%",
    discount: "20%",
  },
];

export const dummyEvent = [
  {
    image: require("@/assets/event1.webp"),
    title: "Lorem ipsum dolor sit.",
    contents: "Lorem ipsum dolor sit amet consectetur.",
    sdate: "24.06.01",
    edate: "24.06.30",
  },
  {
    image: require("@/assets/event2.webp"),
    title: "Lorem ipsum dolor sit.",
    contents: "Lorem ipsum dolor sit amet consectetur.",
    sdate: "24.06.01",
    edate: "24.06.30",
  },
  {
    image: require("@/assets/event3.webp"),
    title: "Lorem ipsum dolor sit.",
    contents: "Lorem ipsum dolor sit amet consectetur.",
    sdate: "24.06.01",
    edate: "24.06.30",
  },
  {
    image: require("@/assets/event4.webp"),
    title: "Lorem ipsum dolor sit.",
    contents: "Lorem ipsum dolor sit amet consectetur.",
    sdate: "24.06.01",
    edate: "24.06.30",
  },
  {
    image: require("@/assets/event5.webp"),
    title: "Lorem ipsum dolor sit.",
    contents: "Lorem ipsum dolor sit amet consectetur.",
    sdate: "24.06.01",
    edate: "24.06.30",
  },
  {
    image: require("@/assets/event6.webp"),
    title: "Lorem ipsum dolor sit.",
    contents: "Lorem ipsum dolor sit amet consectetur.",
    sdate: "24.06.01",
    edate: "24.06.30",
  },
];
